backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
# BACK END LOCAL PARA DESARROLLO - Comentar para hacer build en prod
local_backend: true
# Levantar server local: npx netlify-cms-proxy-server
##
# EDITOR DE SLUGS PARA TITLES DE PÁGINAS
slug:
  encoding: "ascii"
  clean_accents: true
##
# DESHABILITAR VISTA PREVIA EN EDITOR
editor:
  preview: false
##
media_library:
  name: uploadcare
  config:
    publicKey: e581fafc0720c186d59e
media_folder: public/img
public_folder: img
collections:
  - label: "Settings"
    name: "settings"
    extension: "json"
    files:
      - label: "Settings"
        name: "settings"
        file: "content/settings.json"
        fields:
          - label: "Projects order EN"
            name: "projectsOrderEn"
            widget: relation
            collection: "projectsEn"
            value_field: "{{slug}}"
            search_fields: ["title"]
            display_fields: ["title"]
            multiple: true
          - label: "Projects order ES"
            name: "projectsOrderEs"
            widget: relation
            collection: "projectsEs"
            value_field: "{{slug}}"
            search_fields: ["title"]
            display_fields: ["title"]
            multiple: true
          - { label: "Title EN", name: "titleEn", widget: string }
          - { label: "Title ES", name: "titleEs", widget: string }
          - { label: "Description EN", name: "descriptionEn", widget: string }
          - { label: "Description ES", name: "descriptionEs", widget: string }
  - label: "Pages [EN]"
    name: "pagesEn"
    folder: "content/en"
    extension: "json"
    create: false
    fields:
      - { label: "Title", name: "title", widget: string }
      - label: "Page content"
        name: "pageContent"
        widget: list
        label_singular: "Block"
        types:
          - label: "Text block"
            name: "textBlock"
            widget: object
            summary: "{{fields.text}}"
            fields:
              - label: "Text"
                name: "text"
                widget: markdown
                minimal: true
                buttons: ["bold", "italic", "link"]
                editor_components: []
                modes: ["rich_text"]
          - label: "Social media block"
            name: "socialMediaBlock"
            widget: object
            fields:
              - label: "Social media platforms"
                name: "socialMediaPlatforms"
                widget: list
                label_singular: "Platform"
                fields:
                  - { label: "URL", name: "url", widget: string }
                  - label: "Platform"
                    name: "platform"
                    widget: select
                    options: ["Instagram", "Vimeo"]
  - label: "Projects [EN]"
    name: "projectsEn"
    folder: "content/en/projects"
    extension: "json"
    create: true
    fields:
      - { label: "Title", name: "title", widget: string }
      - { label: "Main image", name: "mainImage", widget: image }
      - label: "Specs"
        name: "specs"
        widget: list
        label_singular: "Spec"
        fields:
          - { label: "Spec", name: "spec", widget: string }
      - label: "Project content"
        name: "projectContent"
        widget: list
        label_singular: "Block"
        types:
          - label: "Text block"
            name: "textBlock"
            widget: object
            summary: "{{fields.text}}"
            fields:
              - label: "Text"
                name: "text"
                widget: markdown
                minimal: true
                buttons: ["bold", "italic", "link"]
                editor_components: []
                modes: ["rich_text"]
          - label: "Image block"
            name: "imageBlock"
            widget: object
            fields:
              - { label: "Image", name: "image", widget: image }
          - label: "Vimeo embed block"
            name: "vimeoBlock"
            widget: "object"
            fields:
              - { label: "ID", name: "id", widget: string }
  - label: "Pages [ES]"
    name: "pagesEs"
    folder: "content/es"
    extension: "json"
    create: false
    fields:
      - { label: "Title", name: "title", widget: string }
      - label: "Page content"
        name: "pageContent"
        widget: list
        label_singular: "Block"
        types:
          - label: "Text block"
            name: "textBlock"
            widget: object
            summary: "{{fields.text}}"
            fields:
              - label: "Text"
                name: "text"
                widget: markdown
                minimal: true
                buttons: ["bold", "italic", "link"]
                editor_components: []
                modes: ["rich_text"]
          - label: "Social media block"
            name: "socialMediaBlock"
            widget: object
            fields:
              - label: "Social media platforms"
                name: "socialMediaPlatforms"
                widget: list
                label_singular: "Platform"
                fields:
                  - { label: "URL", name: "url", widget: string }
                  - label: "Platform"
                    name: "platform"
                    widget: select
                    options: ["Instagram", "Vimeo"]
  - label: "Projects [ES]"
    name: "projectsEs"
    folder: "content/es/projects"
    extension: "json"
    create: true
    fields:
      - { label: "Title", name: "title", widget: string }
      - { label: "Main image", name: "mainImage", widget: image }
      - label: "Specs"
        name: "specs"
        widget: list
        label_singular: "Spec"
        fields:
          - { label: "Spec", name: "spec", widget: string }
      - label: "Project content"
        name: "projectContent"
        widget: list
        label_singular: "Block"
        types:
          - label: "Text block"
            name: "textBlock"
            widget: object
            summary: "{{fields.text}}"
            fields:
              - label: "Text"
                name: "text"
                widget: markdown
                minimal: true
                buttons: ["bold", "italic", "link"]
                editor_components: []
                modes: ["rich_text"]
          - label: "Image block"
            name: "imageBlock"
            widget: object
            fields:
              - { label: "Image", name: "image", widget: image }
          - label: "Vimeo embed block"
            name: "vimeoBlock"
            widget: "object"
            fields:
              - { label: "ID", name: "id", widget: string }
